//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITRootsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int ID { get; set; }
        public string Product { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public  Users Users { get; set; }
    }
}
